// default package
package com.seeyon.v3x.indexInterface.domain;
import java.util.Date;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * V3xUpdateIndex generated by MyEclipse - Hibernate Tools
 */

public class V3xUpdateIndex  extends BaseModel implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Fields    
     private Long entityId;
     private Integer type;
     private Date createDate;


    // Constructors

    /** default constructor */
    public V3xUpdateIndex() {
    }

	/** minimal constructor */
    public V3xUpdateIndex(Long id, Long entityId, Integer type) {
        this.id = id;
        this.entityId = entityId;
        this.type = type;
    }
    
    /** full constructor */
    public V3xUpdateIndex(Long id, Long entityId, Integer type, Date createDate) {
        this.id = id;
        this.entityId = entityId;
        this.type = type;
        this.createDate = createDate;
    }

   
    // Property accessors

   public void setId(Long id){
	   this.id=id;
   }
   
   public Long getId(){
	   return id;
   }

    public Long getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
   








}