package com.seeyon.v3x.interfaces.domain;

import com.seeyon.v3x.common.domain.BaseModel;



/**
 * V3xWsCallback generated by MyEclipse - Hibernate Tools
 */

public class WebServiceRegister  extends BaseModel implements java.io.Serializable {


    public static final Integer status_Ok=1;
    
    public static final Integer status_block=2;
    
    public static final Integer status_delete=3;//被删除状态
    
    
	// Fields    

     private Integer appType;
     
     private Long userId;
     
     private String wsUrl;
     
     private String loginId;
     
     private String password;
     
     private Integer status;
     
     private String remark;


    // Constructors

    /** default constructor */
    public WebServiceRegister() {
    }

	/** minimal constructor */
    public WebServiceRegister(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public WebServiceRegister(Long id, Integer appType, Long objectId, String wsUrl) {
        this.id = id;
        this.appType = appType;
        this.userId = objectId;
        this.wsUrl = wsUrl;
    }

   

    public Integer getAppType() {
        return this.appType;
    }
    
    public void setAppType(Integer appType) {
        this.appType = appType;
    }

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getWsUrl() {
        return this.wsUrl;
    }
    
    public void setWsUrl(String wsUrl) {
        this.wsUrl = wsUrl;
    }

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
   








}