package com.seeyon.v3x.common.rss.domain;

import java.util.Date;
import java.util.Set;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * RssCategory generated by MyEclipse - Hibernate Tools
 */

public class RssCategory extends BaseModel implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
    private String name;
    private Integer orderNum;
    private Long createUserId;
    private Date createDate;
    private Long lastUserId;
    private Date lastUpdate;
    private Set categoryChannel;

    // Constructors

    /** default constructor */
    public RssCategory() {
    }


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public Long getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Long getLastUserId() {
        return this.lastUserId;
    }
    
    public void setLastUserId(Long lastUserId) {
        this.lastUserId = lastUserId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
	public Set getCategoryChannel() {
		return categoryChannel;
	}


	public void setCategoryChannel(Set categoryChannel) {
		this.categoryChannel = categoryChannel;
	}
   








}