package com.seeyon.v3x.common.rss.domain;

import java.util.Date;
import java.util.Set;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * RssCategoryChannel generated by MyEclipse - Hibernate Tools
 */

public class RssCategoryChannel extends BaseModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private String name;
     private String url;
     private Integer orderNum;
     private Long createUserId;
     private Date createDate;
     private Long lastUserId;
     private Date lastUpdate;
     private Long categoryId;
     private String description;
     private Set subscribe;

     //
     private RssCategory category;
     
    // Constructors

    public Set getSubscribe() {
		return subscribe;
	}


	public void setSubscribe(Set subscribe) {
		this.subscribe = subscribe;
	}


	/** default constructor */
    public RssCategoryChannel() {
    }


    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public Long getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Long getLastUserId() {
        return this.lastUserId;
    }
    
    public void setLastUserId(Long lastUserId) {
        this.lastUserId = lastUserId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	public RssCategory getCategory() {
		return category;
	}


	public void setCategory(RssCategory category) {
		this.category = category;
	}
		
   
}