package com.seeyon.v3x.common.rss.domain;

import java.sql.Timestamp;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * RssChannelItems generated by MyEclipse - Hibernate Tools
 */

public class RssChannelItems  extends BaseModel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String title;
	private String link;
	private String describse;
	private Timestamp pubDate;
	private String author;
	private String category;
	private String comments;
	private String guid;
	private String source;
	private String enclosure;
	private Long categoryChannelId;
	private Long channelInfoId;


    // Constructors

    /** default constructor */
    public RssChannelItems() {
    }


    public String getTitle() {
    	Pattern p = Pattern.compile("\t|\n");  
    	Matcher m = p.matcher(this.title);  
    	return m.replaceAll("");  
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }



    public String getDescribse() {
		return describse;
	}


	public void setDescribse(String describse) {
		this.describse = describse;
	}


	public Timestamp getPubDate() {
		return pubDate;
	}


	public void setPubDate(Timestamp pubDate) {
		this.pubDate = pubDate;
	}


	public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getGuid() {
        return this.guid;
    }
    
    public void setGuid(String guid) {
        this.guid = guid;
    }

    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    public String getEnclosure() {
        return this.enclosure;
    }
    
    public void setEnclosure(String enclosure) {
        this.enclosure = enclosure;
    }

    public Long getCategoryChannelId() {
        return this.categoryChannelId;
    }
    
    public void setCategoryChannelId(Long categoryChannelId) {
        this.categoryChannelId = categoryChannelId;
    }

    public Long getChannelInfoId() {
        return this.channelInfoId;
    }
    
    public void setChannelInfoId(Long channelInfoId) {
        this.channelInfoId = channelInfoId;
    }

}