package com.seeyon.v3x.common.rss.domain;

import java.util.Date;
import java.util.Set;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * RssChannelInfo generated by MyEclipse - Hibernate Tools
 */

public class RssChannelInfo extends BaseModel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String link;
	private String describse;
	private String title;
	private String language;
	private String copyright;
	private String managingEditor;
	private String webmaster;
	private String pubDate;
	private String lastBuildDate;
	private String category;
	private String generator;
	private int ttl;
	private String imageUrl;
	private String imageTitle;
	private String imageLink;
	private Long categoryChannelId;
	private Set channelItem;


    // Constructors

    /** default constructor */
    public RssChannelInfo() {
    }


    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

  

    public String getDescribse() {
		return describse;
	}


	public void setDescribse(String describse) {
		this.describse = describse;
	}


	public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    public String getCopyright() {
        return this.copyright;
    }
    
    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    public String getManagingEditor() {
        return this.managingEditor;
    }
    
    public void setManagingEditor(String managingEditor) {
        this.managingEditor = managingEditor;
    }

    public String getWebmaster() {
        return this.webmaster;
    }
    
    public void setWebmaster(String webmaster) {
        this.webmaster = webmaster;
    }



    public String getLastBuildDate() {
		return lastBuildDate;
	}


	public void setLastBuildDate(String lastBuildDate) {
		this.lastBuildDate = lastBuildDate;
	}


	public String getPubDate() {
		return pubDate;
	}


	public void setPubDate(String pubDate) {
		this.pubDate = pubDate;
	}


	public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    public String getGenerator() {
        return this.generator;
    }
    
    public void setGenerator(String generator) {
        this.generator = generator;
    }

  

    public int getTtl() {
		return ttl;
	}


	public void setTtl(int ttl) {
		this.ttl = ttl;
	}


	public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getImageTitle() {
        return this.imageTitle;
    }
    
    public void setImageTitle(String imageTitle) {
        this.imageTitle = imageTitle;
    }

    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }

    public Long getCategoryChannelId() {
        return this.categoryChannelId;
    }
    
    public void setCategoryChannelId(Long categoryChannelId) {
        this.categoryChannelId = categoryChannelId;
    }


	public Set getChannelItem() {
		return channelItem;
	}


	public void setChannelItem(Set channelItem) {
		this.channelItem = channelItem;
	}
   








}