package com.seeyon.v3x.common.rss.domain;

import com.seeyon.v3x.common.domain.BaseModel;



/**
 * RssItemStatus generated by MyEclipse - Hibernate Tools
 */

public class RssItemStatus extends BaseModel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer status;
	private Long uesrId;
	private Long rssItemId;
	private Long rssSubscribeId;


    // Constructors

    /** default constructor */
    public RssItemStatus() {
    }


    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getUesrId() {
        return this.uesrId;
    }
    
    public void setUesrId(Long uesrId) {
        this.uesrId = uesrId;
    }

    public Long getRssItemId() {
        return this.rssItemId;
    }
    
    public void setRssItemId(Long rssItemId) {
        this.rssItemId = rssItemId;
    }

    public Long getRssSubscribeId() {
        return this.rssSubscribeId;
    }
    
    public void setRssSubscribeId(Long rssSubscribeId) {
        this.rssSubscribeId = rssSubscribeId;
    }
   








}