package com.seeyon.v3x.common.rss.domain;

import java.util.Date;
import java.util.Set;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * RssSubscribe generated by MyEclipse - Hibernate Tools
 */

public class RssSubscribe extends BaseModel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long userId;
	private String userType;
	private String name;				//预留
	private String url;				//暂且没用
	private Integer showNum;			//预留
	private boolean deploy;			//预留
	private Integer orderNum;			//预留
	private Long createUserId;
	private Date createDate;
	private Long lastUserId;
	private Date lastUpdate;     
	private Long categoryChannelId;
	private Set itemStatus;

    // Constructors

    public Set getItemStatus() {
		return itemStatus;
	}



	public void setItemStatus(Set itemStatus) {
		this.itemStatus = itemStatus;
	}

	/** default constructor */
    public RssSubscribe() {
    }



    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }



    public String getUserType() {
		return userType;
	}



	public void setUserType(String userType) {
		this.userType = userType;
	}



	public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getShowNum() {
        return this.showNum;
    }
    
    public void setShowNum(Integer showNum) {
        this.showNum = showNum;
    }

    public boolean isDeploy() {
		return deploy;
	}



	public void setDeploy(boolean deploy) {
		this.deploy = deploy;
	}



	public Integer getOrderNum() {
        return this.orderNum;
    }
    
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public Long getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Long getLastUserId() {
        return this.lastUserId;
    }
    
    public void setLastUserId(Long lastUserId) {
        this.lastUserId = lastUserId;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

	public Long getCategoryChannelId() {
		return categoryChannelId;
	}



	public void setCategoryChannelId(Long categoryChannelId) {
		this.categoryChannelId = categoryChannelId;
	}



}