package com.seeyon.v3x.plugin.ldap.domain;

import com.seeyon.v3x.common.ldap.config.LDAPConfig;
/**
 * V3xLdapRdn generated by MyEclipse Persistence Tools
 */

public class V3xLdapRdn implements java.io.Serializable
{

    private Long id;

    private String rootAccountRdn;

    private Long orgAccountId;

    private String ldapType;

    private String exId;

    /** default constructor */
    public V3xLdapRdn()
    {
//        id=UUIDLong.longUUID();
        ldapType=LDAPConfig.getInstance().getType();
    }

    /** minimal constructor */
    public V3xLdapRdn(Long id, String rootAccountRdn, Long orgAccountId)
    {
        this.id = id;
        this.rootAccountRdn = rootAccountRdn;
        this.orgAccountId = orgAccountId;
    }

    /** full constructor */
    public V3xLdapRdn(Long id, String rootAccountRdn, Long orgAccountId, String exId)
    {
        this.id = id;
        this.rootAccountRdn = rootAccountRdn;
        this.orgAccountId = orgAccountId;
        this.exId = exId;
    }

    // Property accessors

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getRootAccountRdn()
    {
        return this.rootAccountRdn;
    }

    public void setRootAccountRdn(String rootAccountRdn)
    {
        this.rootAccountRdn = rootAccountRdn;
    }

    public Long getOrgAccountId()
    {
        return this.orgAccountId;
    }

    public void setOrgAccountId(Long orgAccountId)
    {
        this.orgAccountId = orgAccountId;
    }

    public String getExId()
    {
        return this.exId;
    }

    public void setExId(String exId)
    {
        this.exId = exId;
    }

    public String getLdapType()
    {
        return ldapType;
    }

    public void setLdapType(String ldapType)
    {
        this.ldapType = ldapType;
    }

}