package com.seeyon.v3x.edoc.domain;

import java.io.Serializable;
import java.util.Date;

import com.seeyon.v3x.common.domain.BaseModel;


/**
 * EdocMarks generated by MyEclipse - Hibernate Tools
 */
public class EdocMark extends BaseModel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	// Fields    

	private EdocMarkDefinition edocMarkDefinition;
	private Long edocId;
	private String docMark;
	private Integer docMarkNo;
	private Long categoryId;
	private Long createUserId;
	private Date createTime;
	private int status;
	private Long domainId;
	private int markNum=1;
	
	public void setMarkNum(int markNum)
	{
		this.markNum=markNum;
	}
	public int getMarkNum()
	{
		return this.markNum;
	}

    // Constructor



	/** default constructor */
    public EdocMark() {
    }	
    
    // Property accessors

    public EdocMarkDefinition getEdocMarkDefinition() {
        return this.edocMarkDefinition;
    }
    
    public void setEdocMarkDefinition(EdocMarkDefinition edocMarkDefinition) {
        this.edocMarkDefinition = edocMarkDefinition;
    }

    public Long getEdocId() {
        return this.edocId;
    }
    
    public void setEdocId(Long edocId) {
        this.edocId = edocId;
    }

    public String getDocMark() {
        return this.docMark;
    }
    
    public void setDocMark(String docMark) {
        this.docMark = docMark;
    }

    public Long getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getDocMarkNo() {
		return docMarkNo;
	}

	public void setDocMarkNo(Integer docMarkNo) {
		this.docMarkNo = docMarkNo;
	}

	public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

    
}