package com.seeyon.v3x.plugin.ca.caaccount.domain;

import com.seeyon.v3x.common.domain.BaseModel;

/**
 * RssCategory generated by MyEclipse - Hibernate Tools
 */

public class CAAccount extends BaseModel implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
    private String keyNum;
    private long memberId;
    private String whichModule;
    private boolean caState;//CA的状态
    private boolean caEnable;//必须使用CA才能登陆
    private boolean mobileEnable;//移动设备访问不受控制
    private boolean checkEnable;//登陆时同时检查账号密码

    // Constructors


	/** default constructor */
    public CAAccount() {
    }
    
    public boolean isCaState() {
		return caState;
	}

	public void setCaState(boolean caState) {
		this.caState = caState;
	}

	public boolean isCaEnable() {
		return caEnable;
	}

	public void setCaEnable(boolean caEnable) {
		this.caEnable = caEnable;
	}


	public boolean isMobileEnable() {
		return mobileEnable;
	}

	public void setMobileEnable(boolean mobileEnable) {
		this.mobileEnable = mobileEnable;
	}

	public boolean isCheckEnable() {
		return checkEnable;
	}

	public void setCheckEnable(boolean checkEnable) {
		this.checkEnable = checkEnable;
	}

	public String getKeyNum() {
        return keyNum;
    }
    
    public void setKeyNum(String keyNum) {
        this.keyNum = keyNum;
    }
    
    public String getWhichModule() {
        return whichModule;
    }
    
    public void setWhichModule(String whichModule) {
        this.whichModule = whichModule;
    }
    
    public long getMemberId() {
        return memberId;
    }
    
    public void setMemberId(long memberId) {
        this.memberId = memberId;
    }
}