package com.seeyon.v3x.plan.domain;

import java.util.Date;

import com.seeyon.v3x.common.domain.BaseModel;

/**
 * PlanSummary generated by MyEclipse - Hibernate Tools
 */

public class PlanSummary extends BaseModel implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -4857654569140868939L;

	/**
	 * 计划
	 */
	private Plan plan;

	/**
	 * 相关用户 用户id
	 */
	private Long refUserId;

	/**
	 * 相关用户 用户名
	 */
	private String refUserName;

	/**
	 * 总结正文
	 */
	private String text;

	/**
	 * 完成率
	 */
	private Float finishRatio;

	/**
	 * 创建时间
	 */
	private Date createTime;

	// Constructors

	public String getRefUserName() {
		return refUserName;
	}

	public void setRefUserName(String refUserName) {
		this.refUserName = refUserName;
	}

	/**
	 * default constructor
	 * 
	 */
	public PlanSummary() {
	}

	/**
	 * minimal constructor
	 * 
	 * @param createTime
	 */
	public PlanSummary(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * full constructor
	 * 
	 * @param plan
	 * @param refUserId
	 * @param text
	 * @param finishRatio
	 * @param createTime
	 * @param refUserName
	 */
	public PlanSummary(Plan plan, Long refUserId, String text,
			Float finishRatio, Date createTime, String refUserName) {
		this.plan = plan;
		this.refUserId = refUserId;
		this.text = text;
		this.finishRatio = finishRatio;
		this.createTime = createTime;
		this.refUserName = refUserName;
	}

	// Property accessors
	public Long getRefUserId() {
		return this.refUserId;
	}

	public void setRefUserId(Long refUserId) {
		this.refUserId = refUserId;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Float getFinishRatio() {
		return this.finishRatio;
	}

	public void setFinishRatio(Float finishRatio) {
		this.finishRatio = finishRatio;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Plan getPlan() {
		return plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

}