package com.seeyon.v3x.plan.domain;

import org.apache.commons.lang.math.NumberUtils;

import com.seeyon.v3x.common.domain.BaseModel;
import com.seeyon.v3x.organization.domain.V3xOrgMember;

/**
 * PlanRelevantUser generated by MyEclipse - Hibernate Tools
 */

public class PlanRelevantUser extends BaseModel implements java.io.Serializable, Comparable<PlanRelevantUser> {
	
	/**
	 * 计划相关人员（主送、抄送、告知）排序实现：按照类型、排序号升序排列
	 */
	public int compareTo(PlanRelevantUser target) {
		Integer type = NumberUtils.toInt(this.getType(), 0);
		Integer targetType = NumberUtils.toInt(target.getType(), 0);
		if(type.equals(targetType))
			return Integer.valueOf(this.getSortId()).compareTo(Integer.valueOf(target.getSortId()));
		else
			return type.compareTo(targetType);
	}
	
	/**
	 * 计划相关人员（主送、抄送、告知、创建者类型）
	 */
	public static enum UserType {
		/** 主管领导  */
		Leader("1"),
		/** 抄送人员  */
		Copy_To("2"),
		/** 告知人员  */
		Apprize("3"),
		/** 计划发起人  */
		Creator("4"),
		/** 其他  */
		Other("0");
		
		private String value;
		
		UserType(String value) {
			this.value = value;
		}
		
		public String getValue() {
			return this.value;
		}
	}
	
	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -5882308443337232120L;

	/**
	 * 计划
	 */
	private Plan plan;
	
	/**
	 * 排序号
	 */
	private int sortId;

	public int getSortId() {
		return sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	/**
	 * 相关用户 用户id
	 */
	private Long refUserId;

	/**
	 * 计划相关人员： 1、主管领导 2、抄送人员 3、告知人员 4、计划发起人
	 */
	private String type;

	/**
	 * 相关用户 用户名
	 */
	private String refUserName;
	
	private String typeProperty = V3xOrgMember.ORGENT_TYPE_MEMBER;	//parseElements（）这个方法中用到

	// Constructors

	/** default constructor */
	public PlanRelevantUser() {
	}

	/** full constructor */
	public PlanRelevantUser(Plan plan, Long refUserId, String type,
			String refUserName) {
		this.plan = plan;
		this.refUserId = refUserId;
		this.type = type;
		this.refUserName = refUserName;
	}
	
	public PlanRelevantUser(Plan plan, Long refUserId, String type, String refUserName, int sortId) {
		this.plan = plan;
		this.refUserId = refUserId;
		this.type = type;
		this.refUserName = refUserName;
		this.sortId = sortId;
	}

	// Property accessors

	public Long getRefUserId() {
		return this.refUserId;
	}

	public void setRefUserId(Long refUserId) {
		this.refUserId = refUserId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Plan getPlan() {
		return plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	public String getRefUserName() {
		return refUserName;
	}

	public void setRefUserName(String refUserName) {
		this.refUserName = refUserName;
	}

	public String getTypeProperty() {
		return typeProperty;
	}

}