package com.seeyon.v3x.office.asset.domain;

import java.util.Date;


/**
 * TAssetDepartinfo generated by MyEclipse - Hibernate Tools
 */

public class TAssetDepartinfo  implements java.io.Serializable {


    // Fields    

     private Long applyId;
     private Long assetId;
     private Long applyCount;
     private Date assetDeparttime;
     private Date assetBacktime;
     private Long assetDepartcount;
     private Long assetBackcount;
     private String departMemo;
     private Integer delFlag;


    // Constructors

    /** default constructor */
    public TAssetDepartinfo() {
    }

	/** minimal constructor */
    public TAssetDepartinfo(Long applyId, Long assetId, Integer delFlag) {
        this.applyId = applyId;
        this.assetId = assetId;
        this.delFlag = delFlag;
    }
    
    /** full constructor */
    public TAssetDepartinfo(Long applyId, Long assetId, Long applyCount, Date assetDeparttime, Date assetBacktime, Long assetDepartcount, Long assetBackcount, String departMemo, Integer delFlag) {
        this.applyId = applyId;
        this.assetId = assetId;
        this.applyCount = applyCount;
        this.assetDeparttime = assetDeparttime;
        this.assetBacktime = assetBacktime;
        this.assetDepartcount = assetDepartcount;
        this.assetBackcount = assetBackcount;
        this.departMemo = departMemo;
        this.delFlag = delFlag;
    }

   
    // Property accessors

    public Long getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    public Long getAssetId() {
        return this.assetId;
    }
    
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    public Long getApplyCount() {
        return this.applyCount;
    }
    
    public void setApplyCount(Long applyCount) {
        this.applyCount = applyCount;
    }

    public Date getAssetDeparttime() {
        return this.assetDeparttime;
    }
    
    public void setAssetDeparttime(Date assetDeparttime) {
        this.assetDeparttime = assetDeparttime;
    }

    public Date getAssetBacktime() {
        return this.assetBacktime;
    }
    
    public void setAssetBacktime(Date assetBacktime) {
        this.assetBacktime = assetBacktime;
    }

    public Long getAssetDepartcount() {
        return this.assetDepartcount;
    }
    
    public void setAssetDepartcount(Long assetDepartcount) {
        this.assetDepartcount = assetDepartcount;
    }

    public Long getAssetBackcount() {
        return this.assetBackcount;
    }
    
    public void setAssetBackcount(Long assetBackcount) {
        this.assetBackcount = assetBackcount;
    }

    public String getDepartMemo() {
        return this.departMemo;
    }
    
    public void setDepartMemo(String departMemo) {
        this.departMemo = departMemo;
    }

    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
   








}