package com.seeyon.v3x.office.asset.domain;

import java.util.Date;


/**
 * TAssetApplyinfo generated by MyEclipse - Hibernate Tools
 */

public class TAssetApplyinfo  implements java.io.Serializable {


    // Fields    

     private Long applyId;
     private Long assetId;
     private Long applyCount;
     private String assetPurpose;
     private Date assetStart;
     private Date assetEnd;
     private Integer longFlag;
     private Integer delFlag;


    // Constructors

    /** default constructor */
    public TAssetApplyinfo() {
    }

	/** minimal constructor */
    public TAssetApplyinfo(Long applyId, Long assetId, Integer delFlag) {
        this.applyId = applyId;
        this.assetId = assetId;
        this.delFlag = delFlag;
    }
    
    /** full constructor */
    public TAssetApplyinfo(Long applyId, Long assetId, Long applyCount, String assetPurpose, Date assetStart, Date assetEnd, Integer longFlag, Integer delFlag) {
        this.applyId = applyId;
        this.assetId = assetId;
        this.applyCount = applyCount;
        this.assetPurpose = assetPurpose;
        this.assetStart = assetStart;
        this.assetEnd = assetEnd;
        this.longFlag = longFlag;
        this.delFlag = delFlag;
    }

   
    // Property accessors

    public Long getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    public Long getAssetId() {
        return this.assetId;
    }
    
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    public Long getApplyCount() {
        return this.applyCount;
    }
    
    public void setApplyCount(Long applyCount) {
        this.applyCount = applyCount;
    }

    public String getAssetPurpose() {
        return this.assetPurpose;
    }
    
    public void setAssetPurpose(String assetPurpose) {
        this.assetPurpose = assetPurpose;
    }

    public Date getAssetStart() {
        return this.assetStart;
    }
    
    public void setAssetStart(Date assetStart) {
        this.assetStart = assetStart;
    }

    public Date getAssetEnd() {
        return this.assetEnd;
    }
    
    public void setAssetEnd(Date assetEnd) {
        this.assetEnd = assetEnd;
    }

    public Integer getLongFlag() {
        return this.longFlag;
    }
    
    public void setLongFlag(Integer longFlag) {
        this.longFlag = longFlag;
    }

    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
   








}