package com.seeyon.v3x.system.signet.domain;

import java.sql.Blob;
import java.util.Date;

/**
 * V3xSignet generated by MyEclipse - Hibernate Tools
 */

public class V3xSignet extends com.seeyon.v3x.common.domain.BaseModel implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1074860643805559516L;

	// 实际上存的是memberId
	private String userName;

	private String password;

	private String markName;

	private Integer markType = 0;

	private String imgType;

	/**
	 * 用于ORM的
	 */
	private transient Blob markBody;
	
	/**
	 * 原始的，未加密的
	 */
	private byte[] markBodyByte;

	private String markPath;

	private Date markDate;

	private Integer markSize;
	
	private Long orgAccountId;
	
	private Boolean  isDeleted = false; 	//是否已经被删除

	// Constructors

	/** default constructor */
	public V3xSignet() {
	}

	/** minimal constructor */
	public V3xSignet(Long id) {
		this.id = id;
	}
	
	/** full constructor */
	public V3xSignet(Long id, String userName, String password,
			String markName, Integer markType, String imgType, Blob markBody,
			String markPath, Date markDate, Integer markSize,Long orgAccountId) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.markName = markName;
		this.markType = markType;
		this.imgType = imgType;
		this.markBody = markBody;
		this.markPath = markPath;
		this.markDate = markDate;
		this.markSize = markSize;
		this.orgAccountId = orgAccountId;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMarkName() {
		return this.markName;
	}

	public void setMarkName(String markName) {
		this.markName = markName;
	}

	public Integer getMarkType() {
		return this.markType;
	}

	public void setMarkType(Integer markType) {
		this.markType = markType;
	}

	public String getImgType() {
		return this.imgType;
	}

	public void setImgType(String imgType) {
		this.imgType = imgType;
	}

	public Blob getMarkBody() {
		return this.markBody;
	}

	public void setMarkBody(Blob markBody) {
		this.markBody = markBody;
	}

	public byte[] getMarkBodyByte() {
		return markBodyByte;
	}

	public void setMarkBodyByte(byte[] markBodyByte) {
		this.markBodyByte = markBodyByte;
	}

	public String getMarkPath() {
		return this.markPath;
	}

	public void setMarkPath(String markPath) {
		this.markPath = markPath;
	}

	public Date getMarkDate() {
		return this.markDate;
	}

	public void setMarkDate(Date markDate) {
		this.markDate = markDate;
	}

	public Integer getMarkSize() {
		return this.markSize;
	}

	public void setMarkSize(Integer markSize) {
		this.markSize = markSize;
	}

	public Long getOrgAccountId() {
		return orgAccountId;
	}

	public void setOrgAccountId(Long orgAccountId) {
		this.orgAccountId = orgAccountId;
	}

	public Boolean getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}