package com.seeyon.v3x.office.book.domain;

import java.util.Date;


/**
 * TBookDepartinfo generated by MyEclipse - Hibernate Tools
 */

public class TBookDepartinfo  implements java.io.Serializable {


    // Fields    

     private Long applyId;
     private Long bookId;
     private Date bookDeparttime;
     private Date bookBacktime;
     private Long bookDepartcount;
     private Long bookBackcount;
     private String departMemo;
     private Integer delFlag;


    // Constructors

    /** default constructor */
    public TBookDepartinfo() {
    }

	/** minimal constructor */
    public TBookDepartinfo(Long applyId, Long bookId, Integer delFlag) {
        this.applyId = applyId;
        this.bookId = bookId;
        this.delFlag = delFlag;
    }
    
    /** full constructor */
    public TBookDepartinfo(Long applyId, Long bookId, Date bookDeparttime, Date bookBacktime, Long bookDepartcount, Long bookBackcount, String departMemo, Integer delFlag) {
        this.applyId = applyId;
        this.bookId = bookId;
        this.bookDeparttime = bookDeparttime;
        this.bookBacktime = bookBacktime;
        this.bookDepartcount = bookDepartcount;
        this.bookBackcount = bookBackcount;
        this.departMemo = departMemo;
        this.delFlag = delFlag;
    }

   
    // Property accessors

    public Long getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    public Long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Date getBookDeparttime() {
        return this.bookDeparttime;
    }
    
    public void setBookDeparttime(Date bookDeparttime) {
        this.bookDeparttime = bookDeparttime;
    }

    public Date getBookBacktime() {
        return this.bookBacktime;
    }
    
    public void setBookBacktime(Date bookBacktime) {
        this.bookBacktime = bookBacktime;
    }

    public Long getBookDepartcount() {
        return this.bookDepartcount;
    }
    
    public void setBookDepartcount(Long bookDepartcount) {
        this.bookDepartcount = bookDepartcount;
    }

    public Long getBookBackcount() {
        return this.bookBackcount;
    }
    
    public void setBookBackcount(Long bookBackcount) {
        this.bookBackcount = bookBackcount;
    }

    public String getDepartMemo() {
        return this.departMemo;
    }
    
    public void setDepartMemo(String departMemo) {
        this.departMemo = departMemo;
    }

    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
   








}