package com.seeyon.v3x.office.book.domain;

import java.util.Date;


/**
 * TBookApplyinfo generated by MyEclipse - Hibernate Tools
 */

public class TBookApplyinfo  implements java.io.Serializable {


    // Fields    

     private Long applyId;
     private Long bookId;
     private Long applyCount;
     private Date bookStart;
     private Date bookEnd;
     private Integer delFlag;


    // Constructors

    /** default constructor */
    public TBookApplyinfo() {
    }

	/** minimal constructor */
    public TBookApplyinfo(Long applyId, Long bookId, Integer delFlag) {
        this.applyId = applyId;
        this.bookId = bookId;
        this.delFlag = delFlag;
    }
    
    /** full constructor */
    public TBookApplyinfo(Long applyId, Long bookId, Long applyCount, Date bookStart, Date bookEnd, Integer delFlag) {
        this.applyId = applyId;
        this.bookId = bookId;
        this.applyCount = applyCount;
        this.bookStart = bookStart;
        this.bookEnd = bookEnd;
        this.delFlag = delFlag;
    }

   
    // Property accessors

    public Long getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    public Long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Long getApplyCount() {
        return this.applyCount;
    }
    
    public void setApplyCount(Long applyCount) {
        this.applyCount = applyCount;
    }

    public Date getBookStart() {
        return this.bookStart;
    }
    
    public void setBookStart(Date bookStart) {
        this.bookStart = bookStart;
    }

    public Date getBookEnd() {
        return this.bookEnd;
    }
    
    public void setBookEnd(Date bookEnd) {
        this.bookEnd = bookEnd;
    }

    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
   








}