package com.seeyon.v3x.office.admin.domain;

import java.util.Date;


/**
 * MAdminSetting generated by MyEclipse - Hibernate Tools
 */

public class MAdminSetting  implements java.io.Serializable {


    // Fields    

     private MAdminSettingId id;
     private String adminModel;
     private String adminMemo;
     private Date createDate;
     private Date modifyDate;
     private Integer delFlag;

     //other
     private String modelStr;
     private String adminName;
     private String accountName;
     private String departmentName;
     
     private Long domainId;
     private Long accountId;
     
  	public Long getDomainId() {
 		return domainId;
 	}

 	public void setDomainId(Long domainId) {
 		this.domainId = domainId;
 	}
     

    // Constructors

    public Long getAccountId() {
		return accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	/** default constructor */
    public MAdminSetting() {
    }

	/** minimal constructor */
    public MAdminSetting(MAdminSettingId id, String adminModel) {
        this.id = id;
        this.adminModel = adminModel;
    }
    
    /** full constructor */
    public MAdminSetting(MAdminSettingId id, String adminModel, String adminMemo, Date createDate, Date modifyDate, Integer delFlag) {
        this.id = id;
        this.adminModel = adminModel;
        this.adminMemo = adminMemo;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.delFlag = delFlag;
    }

   
    // Property accessors

    public MAdminSettingId getId() {
        return this.id;
    }
    
    public void setId(MAdminSettingId id) {
        this.id = id;
    }

    public String getAdminModel() {
        return this.adminModel;
    }
    
    public void setAdminModel(String adminModel) {
        this.adminModel = adminModel;
    }

    public String getAdminMemo() {
        return this.adminMemo;
    }
    
    public void setAdminMemo(String adminMemo) {
        this.adminMemo = adminMemo;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    
    //other
	public String getModelStr() {
		return modelStr;
	}

	public void setModelStr(String modelStr) {
		this.modelStr = modelStr;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}
   








}